-- VISTA SIMPLE SIN SALARIO Y COMISION
CREATE VIEW V_EMPLEADOS_SIMPLE
AS
	SELECT EMP_NO, APELLIDO, OFICIO, DIR, FECHA_ALT, DEPT_NO
	FROM EMP;
GO
SELECT * FROM V_EMPLEADOS_SIMPLE;

--EN LAS CONSULTAS DE ACCION, NUNCA SE ALMACENAN
--LOS DATOS EN LA VISTA, SINO QUE SE COMUNICA CON
--LA TABLA
INSERT INTO V_EMPLEADOS_SIMPLE VALUES(1112, 'VISTA','VENDEDOR', 7902, GETDATE(), 30)

--VIEW CON INNER JOIN
CREATE VIEW V_EMPLEADOS_DEPARTAMENTO
AS
	SELECT EMP.EMP_NO, EMP.APELLIDO, EMP.OFICIO, EMP.SALARIO, EMP.COMISION,
	DEPT.DNOMBRE, DEPT.LOC, DEPT.DEPT_NO
	FROM EMP
	INNER JOIN DEPT
	ON EMP.DEPT_NO = DEPT.DEPT_NO
GO
SELECT * FROM V_EMPLEADOS_DEPARTAMENTO WHERE LOC= 'MADRID';

--MODIFICAR EL SALARIO DE TODOS LOS EMPLEADOS DE MADRID
--SI LA CONSULTA AFECTA A MAS DE UNA TABLA, NO PUEDE HACERLA
UPDATE V_EMPLEADOS_DEPARTAMENTO SET DNOMBRE = 'LUNES', SALARIO = SALARIO+1 WHERE LOC = 'MADRID'
SELECT * FROM V_EMPLEADOS_DEPARTAMENTO WHERE LOC= 'MADRID';

--ELIMINAR LOS EMPLEADOS DE MADRID
DELETE FROM V_EMPLEADOS_DEPARTAMENTO WHERE LOC = 'MADRID'

--PROCEDIMIENTO PARA BUSCAR EMPLEADOS
-- POR SU SALARIO
CREATE PROCEDURE SP_BUSCADOR_SALARIO
(@SALARIO INT)
AS 
	SELECT * FROM EMP
	WHERE SALARIO >= @SALARIO
GO
EXEC SP_BUSCADOR_SALARIO 350000

--PROCEDIMIENTO PARA INSERTAR
CREATE PROCEDURE SP_INSERT_DEPT
(@NUM INT, @NOM NVARCHAR(50), @LOC NVARCHAR(50))
AS
	INSERT INTO DEPT VALUES (@NUM,@NOM,@LOC)
GO
EXEC SP_INSERT_DEPT 55, 'RRHH', 'OSLO'
