--UTILIZAR TRANSACT DENTRO DE STORED PROCEDURES
CREATE PROCEDURE SP_EVALUAR_SUELDO_EMP
(@APELLIDO NVARCHAR(50)) AS
DECLARE @SUELDO INT
SELECT @SUELDO = SALARIO FROM EMP WHERE APELLIDO = @APELLIDO
IF(@SUELDO < 150000)
BEGIN
	UPDATE EMP SET SALARIO+=10000 WHERE APELLIDO = @APELLIDO
	PRINT 'SUBIDA DE SUELDO DE ' + @APELLIDO + ': ' + CAST(@SUELDO AS NVARCHAR)
END
ELSE IF(@SUELDO > 250000)
BEGIN
	UPDATE EMP SET SALARIO-=2000 WHERE APELLIDO = @APELLIDO
	PRINT 'BAJADA DE SUELDO DE '  + @APELLIDO + ': ' + CAST(@SUELDO AS NVARCHAR)
END
ELSE
BEGIN 
	PRINT 'SALARIO SIN MODIFICACIONES: ' + CAST(@SUELDO AS NVARCHAR)
END
GO
EXEC SP_EVALUAR_SUELDO_EMP 'SANCHA'

--CREAR UN PROCEDIMIENTO PARA INSERTAR UN DOCTOR
--DEBEMOS GENERAR EL ID AUTOMATICAMENTE
--ENVIAMOS EL NOMBRE DEL HOSPITAL
--SI EL HOSPITAL NO EXISTE, NO INSERTAMOS
CREATE PROCEDURE SP_INSERT_DOCTOR
(@APELLIDO NVARCHAR(50), @ESPECIALIDAD NVARCHAR(50),
@SALARIO INT, @NOMBREHOSPITAL NVARCHAR(50))
AS
	DECLARE @IDDOCTOR INT
	DECLARE @IDHOSPITAL INT
	
	SELECT @IDHOSPITAL = HOSPITAL_COD FROM HOSPITAL
	WHERE NOMBRE = @NOMBREHOSPITAL

	IF(@IDHOSPITAL IS NULL)
		BEGIN
			PRINT 'NO EXISTE EL HOSPITAL ' + @NOMBREHOSPITAL
		END
	ELSE
		BEGIN
			SELECT @IDDOCTOR = MAX(DOCTOR_NO) +1
			FROM DOCTOR
			INSERT INTO DOCTOR VALUES
			(@IDHOSPITAL, @IDDOCTOR, @APELLIDO, @ESPECIALIDAD, @SALARIO)
			SELECT * FROM DOCTOR
		END
GO
EXEC SP_INSERT_DOCTOR 'DOMINGUEZ', 'DIAGNOSTICO', 10000000, 'LA PAZZ'

--PROCEDURE DE OUT
CREATE PROCEDURE SP_EMPLEADOS_DEPT_OUT
(@IDDEPT INT, @SUMASALARIAL INT OUT)
AS
	SELECT * FROM EMP
	WHERE DEPT_NO =  @IDDEPT
	--ASIGNAR ALGUN VALOR AL PARAMETRO DE SALIDA 
	--PARA DEVOLVERLO CON VALOR EN LA PETICION
	SELECT @SUMASALARIAL = SUM(SALARIO) FROM EMP
	WHERE DEPT_NO = @IDDEPT
GO
--PARA LA LLAMADA A UN PROCEDIMIENTO ALMACENADO CON
--PARAMETROS DE SALIDA ES NECESARIO UTILIZAR VARIABLES EN
--LA PETICION
DECLARE @RESPUESTA INT
EXEC SP_EMPLEADOS_DEPT_OUT 10, @RESPUESTA OUTPUT
PRINT @RESPUESTA