--FILTRAR TODOS LOS EMPLEADOS DE VENTAS
select COUNT(EMP.EMP_NO) AS TOTALEMPLEADOS,
DEPT.DNOMBRE
FROM EMP
RIGHT JOIN DEPT
ON EMP.DEPT_NO = DEPT.DEPT_NO
GROUP BY DEPT.DNOMBRE


-- QUEREMOS MOSTRAR EL APELLIDO, FUNCION, NOMBRE DE HOSPITAL
-- Y NOMBRE DE SALA DE LOS EMPLEADOS DE LA PLANTILLA
SELECT PLANTILLA.APELLIDO, PLANTILLA.FUNCION, 
HOSPITAL.NOMBRE AS NOMBREHOSPITAL,SALA.NOMBRE AS NOMBRESALA
FROM HOSPITAL
INNER JOIN PLANTILLA
ON HOSPITAL.HOSPITAL_COD = PLANTILLA.HOSPITAL_COD
INNER JOIN SALA 
ON SALA.HOSPITAL_COD = HOSPITAL.HOSPITAL_COD
AND SALA.SALA_COD = PLANTILLA.SALA_COD


SELECT EMP.APELLIDO, EMP.SALARIO FROM EMP WHERE SALARIO = (SELECT MAX(EMP.SALARIO) FROM EMP)

SELECT * FROM EMP WHERE OFICIO = (SELECT OFICIO FROM EMP WHERE APELLIDO='SALA')

--MOSTRAR APELLIDO Y SALARIO DE LOS EMPLEADOS
SELECT APELLIDO, SALARIO AS SUELDO, 'EMP' AS TABLA FROM EMP WHERE SALARIO > 220000 UNION
SELECT APELLIDO, SALARIO, 'DOCTOR' FROM DOCTOR WHERE SALARIO > 220000 UNION
SELECT APELLIDO, SALARIO,'PLANTILLA' FROM PLANTILLA WHERE SALARIO > 220000
ORDER BY SUELDO

SELECT * FROM (SELECT APELLIDO, SALARIO AS SUELDO FROM EMP UNION
SELECT APELLIDO, SALARIO FROM DOCTOR  UNION
SELECT APELLIDO, SALARIO FROM PLANTILLA) QUERY
WHERE QUERY.SUELDO  > 220000


SELECT APELLIDO,FUNCION, CASE T 
							WHEN 'M' THEN 'MAÑANA' 
							WHEN 'T' THEN 'TARDE'
							ELSE 'NOCHE'
						 END AS TURNO
FROM PLANTILLA

INSERT INTO DEPT VALUES ( 50, 'INFORMATICA', 'GIJON')
INSERT INTO DEPT (DEPT_NO, LOC) VALUES ( '60', 'OVIEDO')





INSERT INTO DEPARTAMENTOS
SELECT * FROM DEPT 

SELECT * INTO DEPARTAMENTOS
FROM DEPT


DELETE FROM EMP WHERE DEPT_NO = 
(SELECT DEPT_NO FROM DEPT WHERE DNOMBRE = 'PRODUCCION')

DELETE FROM DEPT WHERE DEPT_NO > 50
SELECT * FROM DEPT

UPDATE DEPT SET DNOMBRE='I+D', LOC = 'VALENCIA'
WHERE DEPT_NO = 50

UPDATE EMP SET SALARIO = SALARIO +1
WHERE OFICIO = 'DIRECTOR'


UPDATE EMP SET SALARIO = (
    SELECT SALARIO FROM EMP WHERE APELLIDO = 'ALONSO'
) WHERE DEPT_NO IN (SELECT DEPT_NO FROM DEPT WHERE LOC = 'BARCELONA') 

SELECT * FROM EMP WHERE DEPT_NO = 20



SELECT APELLIDO, OFICIO, SALARIO, EMP.DEPT_NO AS 'NºDEPT', DEPT.DNOMBRE
FROM EMP
INNER JOIN DEPT ON EMP.DEPT_NO = DEPT.DEPT_NO
WHERE EMP.SALARIO > 300000

SELECT SALA.NOMBRE AS 'NOMBRESALA',HOSPITAL.NOMBRE AS 'Nombre'
FROM SALA
INNER JOIN HOSPITAL ON SALA.HOSPITAL_COD = HOSPITAL.HOSPITAL_COD

SELECT CIUDAD, CUENTA AS 'Nº DE PERSONAS' FROM (SELECT DEPT.LOC AS CIUDAD, COUNT(*) AS CUENTA
FROM DEPT INNER JOIN EMP ON DEPT.DEPT_NO = EMP.DEPT_NO
GROUP BY DEPT.LOC) QUERY
WHERE CUENTA > 4

SELECT DOCTOR.APELLIDO, HOSPITAL.NOMBRE, HOSPITAL.DIRECCION, HOSPITAL.TELEFONO FROM DOCTOR
INNER JOIN HOSPITAL
ON HOSPITAL.HOSPITAL_COD = DOCTOR.HOSPITAL_COD
ORDER BY HOSPITAL.NOMBRE

INSERT INTO DEPT VALUES((SELECT MAX(DEPT_NO) FROM DEPT), 'RRHH','SORIA')
INSERT INTO DEPT VALUES((SELECT MAX(DEPT_NO) FROM DEPT), 'Informática','ALICANTE')

UPDATE DEPT SET LOC = 'Tarbania' WHERE DNOMBRE = 'VENTAS'

INSERT INTO EMP (EMP_NO, APELLIDO, OFICIO, FECHA_ALT, SALARIO, COMISION, DEPT_NO) 
VALUES(
(SELECT MAX(DEPT_NO) FROM DEPT),
'Romeral',
'EMPLEADO',
GETDATE(),
80000,
0.15 * 80000,
(SELECT DEPT_NO FROM DEPT WHERE DEPT.DNOMBRE = 'VENTAS')
)
INSERT INTO EMP (EMP_NO, APELLIDO, OFICIO, FECHA_ALT, SALARIO, COMISION, DEPT_NO) 
VALUES(
(SELECT MAX(DEPT_NO) FROM DEPT),
'Campayo',
'EMPLEADO',
GETDATE(),
80000,
0.15 * 80000,
(SELECT DEPT_NO FROM DEPT WHERE DEPT.DNOMBRE = 'VENTAS')
)


UPDATE EMP SET COMISION = COMISION + (EMP.SALARIO*0.10)
SELECT * FROM EMP

UPDATE PLANTILLA SET SALARIO += 10000
WHERE T = 'N' AND FUNCION = 'Interino'
SELECT * FROM PLANTILLA

INSERT INTO DOCTOR (HOSPITAL_COD, DOCTOR_NO, APELLIDO, ESPECIALIDAD) 
VALUES(
(SELECT HOSPITAL_COD FROM HOSPITAL WHERE NOMBRE = 'La Paz'),
(SELECT MAX(DOCTOR_NO)+1 FROM DOCTOR),
'House',
'Diagnostico'
) 
SELECT * FROM DOCTOR

UPDATE EMP SET SALARIO = (SELECT MIN(EMP.SALARIO)+5000 FROM EMP WHERE EMP.OFICIO = 'EMPLEADO')
WHERE EMP.DEPT_NO = (SELECT DEPT.DEPT_NO FROM DEPT WHERE DNOMBRE = 'VENTAS')

DELETE FROM EMP WHERE EMP.DEPT_NO =  (SELECT DEPT.DEPT_NO FROM DEPT WHERE DNOMBRE = 'I+D')
select * from EMP WHERE EMP.DEPT_NO =  (SELECT DEPT.DEPT_NO FROM DEPT WHERE DNOMBRE = 'I+D')
