/***  CARGAR TODOS LOS CLIENTES (CAMPO EMPRESA)  ***/
SELECT * FROM CLIENTES;
SELECT * FROM pedidos;

/***  FIND CLIENTE BY ID  ***/
CREATE PROCEDURE SP_FIND_CLIENTE_ID
(@NOMBRE NVARCHAR(max))
AS
DECLARE @IDCLIENTE = SELECT CodigoCliente from clientes where Empresa = @NOMBRE
	SELECT * FROM clientes WHERE CodigoCliente = @IDCLIENTE;
GO

/***  MOSTRAR LOS PEDIDOS DE UN CLIENTE  ***/
CREATE PROCEDURE SP_FIND_PEDIDOS_CLIENTE
(@IDCLIENTE NVARCHAR(max))
AS
	SELECT * FROM pedidos WHERE CodigoCliente = @IDCLIENTE
GO

/***  FIND PEDIDO BY ID ***/
CREATE PROCEDURE SP_FIND_PEDIDO_ID
(@IDPEDIDO NVARCHAR(max))
AS
	SELECT * FROM pedidos WHERE CodigoPedido = @IDPEDIDO
GO

/***  UPDATE DE CLIENTE ***/
CREATE PROCEDURE SP_UPDATE_CLIENTE
(@IDCLIENTE NVARCHAR(max), @EMPRESA NVARCHAR(max), @CONTACTO NVARCHAR(max),
@CARGO NVARCHAR(max), @CIUDAD NVARCHAR(max), @TELEFONO INT)
AS
	UPDATE clientes SET Empresa = @EMPRESA, Contacto = @CONTACTO, Cargo = @CARGO,
	Ciudad = @CIUDAD, Telefono = @TELEFONO WHERE CodigoCliente = @IDCLIENTE
GO

/***  INSERTAR PEDIDOS POR CLIENTE ***/
CREATE PROCEDURE SP_INSERT_PEDIDO_CLIENTE
(@IDCLIENTE NVARCHAR(MAX), @FECHA DATETIME, @FORMAENVIO NVARCHAR(MAX), @IMPORTE INT)
AS
	DECLARE @IDPEDIDO NVARCHAR(MAX)
	DECLARE @dt DATE = GETDATE();

	SET @IDPEDIDO = CONVERT(VARCHAR(10),@dt,107)

	INSERT INTO pedidos VALUES(@IDPEDIDO,@IDCLIENTE, @FECHA, @FORMAENVIO, @IMPORTE)
GO

/***  DELETE DE UN PEDIDO (POR ID) DE UN CLIENTE ***/
CREATE PROCEDURE SP_DELETE_PEDIDO_CLIENTE
(@IDPEDIDO NVARCHAR(MAX))
AS
	DELETE FROM pedidos WHERE CodigoPedido = @IDPEDIDO
GO

